### ISSUE TITLE
Add Project Flux Gear

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#100]
http://minecraft.curseforge.com/mc-mods/222948-thermal-tinkerer

GitHub Repo: https://github.com/TeamMagnequasar/ProjectFluxGear

Because holy crap at ~~[dem plans](https://www.dropbox.com/s/jelzhlmnwr01gdm/Thermal%20Tinkerer%20Plans.txt)~~ (link 404's now) man.  We'll have to wait until more is worked on, because as of right now it's nothing but simple worldgen, but if they develop this into what is listed in those plans, it could be GregTech levels of content, for Thermal Expansion based packs.

Plus having more ores/alloys to work from is always nice.

**Comment by UndeadZeratul** [comment]
Updated Title to reflect new mod name, added GitHub repo link, and removed question label as it's no longer a question really, since GT is out of the picture.

**Comment by Nincodedo** [comment]
No updates from the project since January. We can reopen if it gets updates.
