### ISSUE TITLE
Add Poor Ores

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#125]
They only give a nugget's worth, instead of a full ingot or two.  If it's possible to do, we could even incorporate them into CoFH's custom oregen, possibly alongside their dense ore counterparts.

We'll want to balance it so that you mostly get normal ores, slightly less poor ores, and even less dense ores.

**Comment by UndeadZeratul** [comment]
Now that we've removed GT, we can re-add Poor Ores, and possibly use CoFH to generate small veins of them uniformly across all chunks?

**Comment by Nincodedo** [comment]
I'd like to add this to 1.5 since it affects worldgen.

**Comment by UndeadZeratul** [comment]
ah, ok then I'll re-assign it to 1.5, add it to my local dev environment, and see if I can set it up before we push 1.5 to master
