### ISSUE TITLE
Disable/Nerf MFR Mining Laser

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#126]
Gettin' shit fo' free, yo!

We need to either make the laser and/or its pre-chargers really, REALLY hard to craft (dragon essence altar at least); cost an INSANE amount of power; make the foci really expensive; or disable them altogether.  Considering it only requires power to basically create resources, it should be the LAST automated mining machine built (yes, even after the Digital Miner or the Ender Quarry).

**Comment by Nincodedo** [comment]
Talked with @UndeadZeratul about this earlier today but wanted to document it. Possibly we could remove the laser focuses so the Mining Laser acts more like the Orechid from Botania and is a little less OP.

**Comment by Nincodedo** [comment]
Did we want to do anything besides remove the foci?

**Comment by UndeadZeratul** [comment]
Considering the dimension restrictions, I think that, at least for now, we should be ok.  I'll close this and call it done until further notice.
