### ISSUE TITLE
Chisel Void Stone and ComputerCraft Wireless Modem share a recipe

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#143]
Due to this only the wireless modem can be crafted. Minetweaker recipe to craft the other?

**Comment by UndeadZeratul** [comment]
If it's always preferring the modem, then we can simply add a separate recipe for the void stone.  If it ever prefers the other, then we might have to remove both recipes, then manually add them both back in (since at that point we can't guarantee that just adding a separate recipe will fix the problem 100% of the time).

**Comment by Nincodedo** [comment]
I'm assuming the wireless modem recipe is being preferred because ComputerCraft registers after Chisel. I'm not sure if it will always prefer that though. To be sure, we should remove both and manually add both, with the void stone being something different. Currently they're both smooth stone surrounding an ender pearl.

**Comment by UndeadZeratul** [comment]
Yeah, and we can actually make the wireless modem harder considering it's a piece of electronics essentially.

**Comment by Nincodedo** [comment]
And we'll need to consider if we're even going to keep ComputerCraft since we have OpenComputers. If so, I agree that we need to make the recipes harder.

**Comment by UndeadZeratul** [comment]
Considering I don't use either, I'd be fine with either.  For the sake of having such automation capabilities through these mods, I'd rather go with OC, than CC.  The fact that OC is becoming ever more popular, with more and more support coming in for it, I'm also leaning more towards it.

**Comment by UndeadZeratul** [comment]
We no longer have CC.  Therefore, this issue can be closed.
