### ISSUE TITLE
Remove PoorOres

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#144]
GregTech handles this now and it's no longer needed.

**Comment by UndeadZeratul** [comment]
Agreed.  I've been having minor issues with how Poor Ores handles things, as it's slightly different than DenseOres.  Also, GT's "Small Ore" blocks are nice and work with each stone type added from GT (stone, red granite, netherrack, end stone,etc.)

I'm ok with removing poor ores.
