### ISSUE TITLE
Welp, since Orichalcum is possibly no longer a "Fantasy" metal, what do?

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#146]
http://news.discovery.com/history/archaeology/atlantis-legendary-metal-found-in-shipwreck-150106.htm

Looks like the ingots they found, if they are indeed orichalcum, are a copper alloy, consisting of about 75-80% copper, 15-20% zinc, and traces of lead, iron, and nickel.

Due to this new information, do we want to have orichalcum be an ore still? or do we want to make it an alloy?  If we make it an alloy, I'm thinking something along the lines of 2 brass (75% copper, 25% zinc - close enough), and 2 tiny piles of each lead, iron, and nickel.  This would make 2 piles of orichalcum (a small amount of metal is lost, though... hmm).

Obviously this would be easier in the smeltery, as we're not limited to 9 items.  At that point you could just do 112 mB of copper, 24mB of zinc, 8mB of lead, 8mB of iron, 8mB of iron; giving 160 mB of orichalcum, or just over 1 ingot.

Taking some liberties, we might be able to replace a few for the sake of crafting mechanics.  Copper and Zinc make Brass, and Iron and Nickel make Invar, so why not do 7 brass, 1 invar, 1 lead?  This would obviously be way too high on the lead and invar portion, but it'd give out 9 orichalcum dusts, and would be consistent alongside the rest of our crafting recipes.

**Comment by Nincodedo** [comment]
Still fantasy, sinking ship has magic metal on it.

**Comment by UndeadZeratul** [comment]
Meh, whatevs...  We don't need an issue for this.  If we plan on changing it in the future, we'll cross that bridge then.
