### ISSUE TITLE
Add Galacticraft Addon - More Planets

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#147]
http://forum.micdoodle8.com/index.php?threads/1-7-10-more-planets-galacticraft-add-on.4502/

More planets to explore, dungeons to plunder, and bosses to fight.  Also maybe we can move ores around some more :3

The more exploration and diversifying of resources we can do, the better, IMO.  We want to encourage exploration, so if we can go to new planets to branch off on some mods, why not?

Same with the caveworld dimension, or deep dark; they're not part of the main progression, but going off the "main path" should be rewarding.  You can either just climb the harvest level tree and get your desichalkos pick and never have to worry about stuff again, or you can go exploring and find new things to explore, build, tinker with.

**Comment by Nincodedo** [comment]
Ignore that first commit.
