### ISSUE TITLE
Add Galacticraft Addon - Galactigreg

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#148]
http://forum.industrial-craft.net/index.php?page=Thread&threadID=11039

This way we can push some of the GT ores to later dimensions, and not have them clog up our overworld (like naquadah, or tungsten)

**Comment by Nincodedo** [comment]
Not sure if it was just my computer or what but when I added this I got the wooorst world gen lag I've ever seen. We'll have to wait for an updated.
