### ISSUE TITLE
MineTweaker scripts have long load times

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#149]
In total our scripts take 2 minutes to load on my computer, which is pretty high end and shouldn't have this issue. The following scripts are the biggest offenders.

- EnderIO
- GC3
- TiC
- AE2 Phoenix

We'll need to see if we can optimize these somehow or move their tweaks into Nincrafty Things.

**Comment by Nincodedo** [comment]
With the removal of GT, this will be resolved.

**Comment by UndeadZeratul** [comment]
We hope so...  I might test the lines we removed, in case GT had an effect on them
