### ISSUE TITLE
Add Tinker's Defense

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#151]
http://www.curse.com/mc-mods/minecraft/226910-tinkers-defense

**Comment by UndeadZeratul** [comment]
I think we're also going to need Mine&Blade for that, since that's what the shields are for.

**Comment by Nincodedo** [comment]
Ah, true.

http://minecraft.curseforge.com/mc-mods/59710-mb-battlegear-2
