### ISSUE TITLE
Hand of Ender requires an unobtainable item

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#154]
http://i.imgur.com/wp32Oq5.png

The vanilla Ender Chest cannot be crafted.

**Comment by UndeadZeratul** [comment]
Due to [this](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/develop/config/EnderStorage.cfg#L7-L11) the chest should be craftable, yet unplaceable.  My guess is GregTech interfered with the crafting recipe, which might no longer be an issue.

**Comment by Nincodedo** [comment]
Gotcha, I'll check tonight to make sure this is resolved.

**Comment by Nincodedo** [comment]
Confirmed it can be crafted, however it does not show up in NEI.

**Comment by UndeadZeratul** [comment]
strange...
