### ISSUE TITLE
Add RFTools to replace Mystcraft

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#161]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-powerful

Saw this on reddit the other night, looks interesting, and could be a good way to balance out having our own personal dimensions, as well as finally having some sort of endgame power sink.

Of course, if there's issues or it just doesn't play nicely, we can just keep Mystcraft.

**Comment by UndeadZeratul** [comment]
Changed title and added mod removal tag to reflect that RF Tools will be brought in to replace Mystcraft, if for nothing else but to try and balance out the custom dimensions.

**Comment by Nincodedo** [comment]
RFTools has been added but we may need to go through recipes and change stuff. We can reopen an issue if we find anything that needs changing.
