### ISSUE TITLE
Basic Control Circuit Recipe Missing

### ISSUE THREAD

**Issue by PepperYourAngus** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#164]
You cannot add redstone to osmium in the metallurgic infuser, this happened only after the update where we removed GT.

**Comment by UndeadZeratul** [comment]
By Default, they're just 2 redstone and the alloy, as shown [here](http://wiki.aidancbrady.com/wiki/Control_Circuit).  If this doesn't work, then we'll have to add something back in.

**Comment by Nincodedo** [comment]
Confirmed fixed.
