### ISSUE TITLE
Replace Too Much Loot with Custom Chest Loot

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#168]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282771-forge-father-toasts-mods-special-mobs-mob

Because this way we can actually ADD new things to the loot lists, instead of just taking them away, also DMiller is reported to be leaving MC Modding, so lack of updates == bad.

Nin EDIT:
- [ ] Remove Too Much Loot
- [ ] Add Custom Chest Loot
- [ ] Remove bad chest loot, such as OP or super common useless items

**Comment by Nincodedo** [comment]
So after adding Custom Chest Loot, it seems the config files are not nearly as useful as Too Much Loot. It does let us add loot but itlooksugly. Do we have a need for this still?

**Comment by UndeadZeratul** [comment]
if it's that much worse to work with, we probably won't need it.  Besides, could we just register items into chest loot via Nincrafty things?

**Comment by Nincodedo** [comment]
Yeah, just need the full name and to load after whatever mod we're registering items for. I'll close this for now and we can open up issues on Nincrafty Things for items we want to register.
