### ISSUE TITLE
Add The Aether II

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#178]
www.AetherII.com/downloads

Because it's a cool mod, and could add cool ways to introduce new resources or progression paths, and just all around new things to explore and do, including functions and boss fights.

**Comment by UndeadZeratul** [comment]
Changed Milestone to release 1.0.0, due to the fact that this mod's dev team has a history of slow releases, and that we don't want to add a mod that can't fix bugs quickly, or cause us to remove it down the road and have to rip out a lot of integration because of it.  If they can prove they're going to update frequently, we'll consider them.

**Comment by Nincodedo** [comment]
I know we added this issue a while ago but do we still want this with the other dimension changes we're making?

**Comment by UndeadZeratul** [comment]
If we can disable the equipment changes, I'd be ok with more exploring and adventuring for magic mods.  We seem to be tech-heavy in terms of content, but we have a lot of magical dimensions as well.

I think the question will be do we want more dimensions or more content for the magic mods we include?  I'd like to include the Aether because it's a decent dimension mod, and we don't have any sky dimensions, either.  However, because the dimension is made up entirely of custom blocks, we can't easily put ores in that dimension in a way that's not too jarring or out of place.  We could try and integrate their resources in with some other magic mod recipes, but then it'll start looking like magic mods are spread out really thin across so many different dimensions, whereas tech mods are basically within the nether and deep dark.  I think we should try and focus more on tech dimensions, rather than magical ones, if we want to add more.

I'm all for adding it still, but I think we should really start looking at what dimensions we have and what we can get out of them in the end.

**Comment by UndeadZeratul** [comment]
Upon further review, I'm thinking our current amount of dimensions, exploration, and adventuring content is comfortable enough.  That and the fact that The Aether modifies so much with the player's equipment, and the mod's content can be broken with the pack's flying options, we no longer feel The Aether belongs in NEB2.
