### ISSUE TITLE
Rebalance Pack Progression

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#186]
As per several discussions between myself and @Nincodedo, we've decided that instead of having the pack progress along a single path, we're going to divide the pack into two main focuses; magic and tech.  The themes we've developed so far with resources and crafting recipes will remain as they are, but they will no longer take place after each other.  Players shouldn't HAVE to build a base with everything from the magic stage before they can work on a tech base; nor should they have to rebuild their entire ore processing system just to go through 2x ore processing all over again, when they've already progressed through the magic mod ore processing tiers.

By splitting up the progression, we'd be offering more choices for players to build their bases out of, while keeping several gameplay mechanics and concepts even along the two parallels.  Players should be able to jump across these parallels with minimal effort (aside from the normal exploring and gathering of the appropriate resources) and pick up roughly where they were conceptually before.

We still want to encourage exploration, so having certain resources contained within their themed dimensions is still our main goal.  We just feel having one long line of progression doesn't fit the overall concept of the pack.

Nin EDIT:

Adding a small task list for this. Please feel free to add to this.

- [x] Add Tropicraft
- [x] Add Witchery
- [ ] Shift world gen to include these dimensions
- [x] Shift around harvest levels to adjust for splitting up progression paths

**Comment by Nincodedo** [comment]
"Players should HAVE to build a base with everything from the magic stage before they can work on a tech base"

shouldn't?

**Comment by UndeadZeratul** [comment]
whoops, fixed.

**Comment by Nincodedo** [comment]
:+1: I like this change, but I think we'll need more specific dimensions to accommodate this change. We've talked about adding Tropicraft and Witchery for the Tropics and Dream World dimensions to fill this purpose.

**Comment by UndeadZeratul** [comment]
As well as possibly the new Betweenlands mod, although that may just be more general adventuring.  Considering the "balance" the team wants to achieve in their mod, we may have to explore it very early game, before we get too deep into mods; or just bring vanilla-like items.  Either way, I'd like to see what their dimensions can provide us as well.

Tropicraft could be useful as a magic utility dimension, which would parallel the Deep Dark being a tech utility dimension.  We should also look into the potential of moving a magic mod to that dimension, or at least some sort of high-powered resources/items from magic mods in general.

The Dream World will be our late game magic dimension, sort of like how Galacticraft has the asteroids and all that; it'll contain some of the most prized resources, considering the difficulty of not only getting that dimension stable, but also bringing anything you've gathered from there back to the real world.

**Comment by Nincodedo** [comment]
Adding a small task list for this. Please feel free to add to this.

- [ ] Add Tropicraft
- [ ] Add Witchery
- [ ] Shift world gen to include these dimensions
