### ISSUE TITLE
Basic TE machines have no recipe

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#193]
Only the higher tier machines have recipes.

**Comment by Nincodedo** [comment]
After some testing, I found that [these lines](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/2aeb8b8687cae4dcf532bdf032a4c808b01e35f8/scripts/NEB2%20TE4%20Tweaks.zs#L214-L220) are the ones removing the basic recipes.

**Comment by UndeadZeratul** [comment]
I can see how the signalum lock recipe is removed, but I still fail to see how that removes the basic recipes...  Oh well, we want to change them anyways, so we'll just have to bump up the priority on them.
