### ISSUE TITLE
Botania book isn't accurate for our Minetweaker changes

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#196]
We'll have to use Minetweaker to update the recipe pages with our changes.

http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support:Lexica_Botania

**Comment by UndeadZeratul** [comment]
Adding this to the 0.7.1 milestone just so we can keep track of it
