### ISSUE TITLE
Tome of Knowledge recipe needs changing

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#199]
As discussed with @UndeadZeratul, infusion crafting of all the other mod books into a wand focus of equal trade would make this much later game.

**Comment by UndeadZeratul** [comment]
Plus it just fits the theme of trading things of some value with something else of equal value.  On top of that the idea of merging the knowledge of everything in the known "world" (aka, all the mod books we have that are applicable) into a single tome about equivalent exchange.

Combine that with needing to feed the infusion altar with large amounts of the primal Vis aspects, as well as the knowledge and trade aspects and a high amount of instability would make this an expensive and somewhat risky endeavor, but worthwhile as well; fitting for transmutation circles alchemy.

**Comment by Nincodedo** [comment]
We are currently unable to remove the Tome from the Aludel, so we'll have to change the recipe of the chalk instead to keep EE3 later.

**Comment by UndeadZeratul** [comment]
With the update for Nincrafty Things, we can successfully remove the Tome of Knowledge recipe from the Aludel, so we can now actually switch this back to adding in a new recipe for the tome.

**Comment by Nincodedo** [comment]
Suggestions for what the recipe should be? I was thinking Dire Crafting table with all the books from every mod.

**Comment by UndeadZeratul** [comment]
That would certainly fit the theme, do we have any sort of mystical endgame material to bind the books together?

**Comment by UndeadZeratul** [comment]
I've nerfed the Tome quite a bit, but the recipe can obviously still change.  Either way, it's harder than it was before, so that should be good.  I'll close this for now since we've made it cost the books and resources from various mods.
