### ISSUE TITLE
Fluxed Crystals crashes on server startup

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#200]
Downgrading to 0.0.5k until https://github.com/jaredlll08/Fluxed-Crystals-Reborn/issues/4 is fixed.

**Comment by Nincodedo** [comment]
This has still not been fixed. We'll push this issue to the 1.7 beta milestone for now.

**Comment by UndeadZeratul** [comment]
Well, are we resetting for 1.6?  since ATG needs to be on a new map? or are we just going to do that for 1.7?

**Comment by Nincodedo** [comment]
I really don't want to reset but I think we have to due to ATG, and if we reset then we won't need to care about Fluxed Crystals breaking the item mapping. So I'll update this and start a new map.

**Comment by UndeadZeratul** [comment]
I don't necessarily want to either, I was just curious what the plan was.  I get it though, if we want to test the worldgen with ATG in it before we go to 1.7, I don't know if we have a choice, really.

**Comment by Nincodedo** [comment]
By removing Fluxed Crystals, starting the world, and adding the new Fluxed Crystals, I was able to get around this crash. However any currently placed Fluxed Crystal blocks have been removed. I don't think there were too many.

**Comment by UndeadZeratul** [comment]
Were there _any_?

**Comment by Nincodedo** [comment]
Dunno, probs not.

**Comment by UndeadZeratul** [comment]
I'm not terribly worried, since even if there were any, we're planning on resetting for 1.7 anyways.
