### ISSUE TITLE
Dragon egg recipe

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#202]
Dragon heart infusion? Need more ideas

**Comment by UndeadZeratul** [comment]
With Draconic Evolution out of the pack, what do we want to do with this?

**Comment by Nincodedo** [comment]
To be honest I'm not sure why I wanted a dragon egg recipe so........ Nothing...?

**Comment by UndeadZeratul** [comment]
For really endgame stuff, since there was a possibility of getting more than one with DE installed.  There's still the Xeno's Reliquary Tome of the Alkahest that can probably dupe them, but other than that, we're stuck with at most one egg.

**Comment by Nincodedo** [comment]
If we have the tome to dupe them then this isn't really needed.

**Comment by UndeadZeratul** [comment]
I checked ingame last night, there's no uses for the egg, and no current tome recipe to dupe it.  Xeno must have removed it during an update (considering we haven't played with it since 1.5-1.6).

**Comment by Nincodedo** [comment]
We should add that tome recipe back in. If anything maybe make it harder than it was before.

**Comment by UndeadZeratul** [comment]
But we still don't have a reason to have more than one, do we?  There's no current use for it; what would you want to use them for?

**Comment by Nincodedo** [comment]
I dunno but if I don't have one I can't use it. :P I figure once we get into a closed beta, people will run into really really OP stuff that we haven't found yet. We could just put those behind a dragon egg in the recipe to gate them.

**Comment by UndeadZeratul** [comment]
So that not only do you need to kill the dragon, but you need to be careful not to use up all of the eggs because then you won't be able to summon another one... hmm, would we want a recipe of some form or another to MAKE an egg?

**Comment by Nincodedo** [comment]
Yes. Possibly requiring every magic mod in some way. Maybe Ender Air from Botania, some Blood Magic items and other things made with infusion crafting.
