### ISSUE TITLE
AE2 script overhaul

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#204]
We either want to remove or heavily modify our current AE2 scripts. It makes AE2 a little too difficult and annoying to the point where it's not fun.

**Comment by UndeadZeratul** [comment]
I'm thinking a mixture of AE2 materials (quartz and whatnot), platinum, and maybe a bit of both magic and tech metals should do it.  Much better than random mekanism and TE4 materials like it's set to currently.
