### ISSUE TITLE
[1.6 Beta] Pistons do not have a recipe

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#215]

**Comment by UndeadZeratul** [comment]
Apparently I can't spell, because I tried fixing it [here](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/develop/scripts/NEB2%20Vanilla%20Tweaks.zs#L49), but typo'd.
