### ISSUE TITLE
Fix biome IDs

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#219]
Dis is bad https://www.reddit.com/r/feedthebeast/comments/3f9ar7/about_biome_ids_and_17s_use_of_modified_biomes/

**Comment by UndeadZeratul** [comment]
Due to new BoP biomes, and the fact that Galacticraft biomes weren't shifted around, I'm going to re-open this and double check to make sure nothing's conflicting or set incorrectly.

**Comment by UndeadZeratul** [comment]
I've gone through and shifted around almost every Biome ID I could find.  If we have any conflicts or any odd biome behavior, we can open a new issue, but seeing as how the biomes should follow the spreadsheet, I doubt we'll have any hard conflicts, and odd behavior should only really happen to biomes used in the overworld; of which we've limited that overlap as much as we can.

I'm going to close this for now
