### ISSUE TITLE
Review world gen

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#231]
ATG seems to be giving varying results on world gen. Some seeds make sense, some seeds have snow right near spawn and giant gravel beaches that should be oceans.

- [x] Break up these two into hot/cold https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/cf951ee67ea3d62932e113d94293e9f610c44d99/config/atg/generator.cfg#L77-L97
- [ ] Shift cold areas out farther

**Comment by UndeadZeratul** [comment]
Guess I'll be taking a look at ATG now rather than later...  At least it's the only real thing we need to look at currently.

**Comment by UndeadZeratul** [comment]
The framework has been mostly set in place; I think from here on out it should just be filling out the remaining biomes and sub-biomes, and fudging with the biome category suitability parameters until we're happy with it.  So far though I've got the bulk of the rework in place, including a better distribution of temperatures and biome height cut-offs.

**Comment by Nincodedo** [comment]
Break up these two into hot/cold https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/cf951ee67ea3d62932e113d94293e9f610c44d99/config/atg/generator.cfg#L77-L97
