### ISSUE TITLE
Generate Nincrafty Things Quartz Ore

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#233]
Overworld only, unsure of how much.

**Comment by UndeadZeratul** [comment]
Considering it's basically a utility ore, and not anything used in progression, it should be ok to generate a plentiful amount of it, somewhere around the same amount as coal, or even Certus/Nether Quartz.

**Comment by UndeadZeratul** [comment]
Dense/Poor Ore versions of Quartz have been added.
