### ISSUE TITLE
PoorOres with a texture pack causes crashes

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#248]
Reported here: https://www.reddit.com/r/feedthebeast/comments/3sllgo/neb2_the_nincraft_team_is_looking_for_some_beta/cwyi5nw

Crash log: http://pastebin.com/d5MJZpVz

**Comment by Nincodedo** [comment]
Semi resolved... We'll need to update PoorOres to actually fix this. https://www.reddit.com/r/feedthebeast/comments/3sllgo/neb2_the_nincraft_team_is_looking_for_some_beta/cwyn6g9

**Comment by Nincodedo** [comment]
We may be able to fix this by supplying textures for PoorOres. We'll have to do some testing to see what works.

**Comment by kaikue** [comment]
The problem occurs when a higher-resolution texture pack is missing textures for some ores (in my case, Quartz from NincraftyThings). Adding a texture for that fixed the problem.

https://www.reddit.com/r/feedthebeast/comments/3sllgo/neb2_the_nincraft_team_is_looking_for_some_beta/cwzg78z
