### ISSUE TITLE
Please update your chisel

### ISSUE THREAD

**Issue by Drullkus** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#249]
Please [update your chisel](http://minecraft.curseforge.com/projects/chisel) so we don't have to deal with bogus reports of people using an outdated branch of Chisel. :)

I would also like to recommend [this mod called More Chisels](http://minecraft.curseforge.com/projects/morechisels). Adds more chisels from varying tool materials, including ones powered by various mods.

**Comment by Nincodedo** [comment]
This will be included in our weekly release on 11/20. Thanks!

**Comment by Drullkus** [comment]
You should also check out More Chisels o:
