### ISSUE TITLE
OpenComputers making the pack crash

### ISSUE THREAD

**Issue by EnderCreeper15** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#252]
http://pastebin.com/i403MMxx

**Comment by EnderCreeper15** [comment]
Forgot to mention: all my friends experience this issue too, and removing OpenComputers makes it work.

**Comment by UndeadZeratul** [comment]
What launcher are you using?  I googled the error and it seems it might be sure to how the Curse voice launcher loads the files.

**Comment by Nincodedo** [comment]
Are you still having this issue?

**Comment by dandudek7** [comment]
No, I started using the Nincraft launcher.

**Comment by Nincodedo** [comment]
Good enough for me :P
