### ISSUE TITLE
Agricraft still has Pneumaticraft plants

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#260]
Which don't exist so this happens http://pastebin.com/iWcRK5Gr

**Comment by UndeadZeratul** [comment]
I think we just need to update Agricraft, it seems they removed PneumaticCraft compatibility in a newer version, which should solve this issue.

https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/commit/c86b6bf352193da2a4500a61da3a03bd5bab9aae#diff-7e327238580f832b0b1ba35a845f7ca8R84
