### ISSUE TITLE
Botania weight lens can be used to harvest any block

### ISSUE THREAD

**Issue by kaikue** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#263]
A Mana Spreader with a Weight Lens will apply gravity to any blocks the mana blast passes through. If the block falls onto a torch or equivalent, it will drop as an item regardless of harvest level. You might want to make the weight lens require titanium.

**Comment by UndeadZeratul** [comment]
It's almost like blocks shouldn't break by a wooden torch...

**Comment by Nincodedo** [comment]
Accidentally did this on both branches, oh well.
