### ISSUE TITLE
AOBD overwriting M4 metals in smeltery; cannot cast Metallurgy tools.

### ISSUE THREAD

**Issue by Booyadude** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#268]
![2015-11-28_12 08 09](https://cloud.githubusercontent.com/assets/8705282/11453321/c3ee7a30-95cb-11e5-8b4b-52f94bc78869.png)

Since Metallurgy has its own molten metals, AOBD's versions can probably safely be disabled in the configs.

**Comment by UndeadZeratul** [comment]
Should be fixed from https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/commit/114c03af450a2a7f4867f855954098bc1e8f53f8
