### ISSUE TITLE
Enderium blend has two crafting recipes

### ISSUE THREAD

**Issue by kaikue** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#272]
Enderium dust is not listed as an alloy dust in the Crafting Unification Tweaks script, so its original recipe is not disabled.

**Comment by Nincodedo** [comment]
:clap:

**Comment by UndeadZeratul** [comment]
I must've put it into the TiC unification script and forgot about it in the crafting one too... WHOOPS

**Comment by kaikue** [comment]
Smeltery alloying in NEI also shows the old recipe.

**Comment by UndeadZeratul** [comment]
IGNORE ME!

I'll make sure they both work, then.

**Comment by UndeadZeratul** [comment]
Ok this is weird, Enderium is in the script, as shown [here](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/master/scripts/NEB2%20Crafting%20Unification%20Tweaks.zs#L2027-L2029).  Will look into why it's not working nonetheless, maybe it's a script error that causes it to fail.
