### ISSUE TITLE
Remove Lycanite's Mobs Configs

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#70]
Now that we've gotten rid of it, let's remove their configs, as well as the templates for the DLDungeons so that they cause and issues; also this will just clean up the repo a bit and not leave so many orphaned configs lying around.

**Comment by Nincodedo** [comment]
Did we still need to do things with this?

**Comment by UndeadZeratul** [comment]
uhh, hmm, I guess not; I removed the mobs from the dungeon spawners, and we removed the DLDungeon configs, right?  That should be all of them.

**Comment by Nincodedo** [comment]
goooodenoughformeeee
