### ISSUE TITLE
Implement Nincodium

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#72]
We'll add our own ingots, Nincodium. They'll most likely be an alloy, probably a blend of lapis and cobalt. This might need to be broken out to it's own mod at some point but I'd like to try and get this added just because it would be cool. :) We should be able to use Tabula Rasa and Minetweaker for the time being.

**Comment by UndeadZeratul** [comment]
Removing Worldgen tag, as we've made Nincodium an alloy, and thus needs no worldgen.

**Comment by Nincodedo** [comment]
This is for the most part done. Nincodium has been added as an alloy so everything in obtainable. I'll call this closed.
